import path from "node:path";
import { fileURLToPath } from "node:url";
import { config } from "dotenv";
import {
  assertIntegerRange,
  assertNumberOrder,
  assertNumberRange,
  createRuntimeEnvReader,
} from "@amb/shared";

const rootEnvPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..", ".env");
config({ path: rootEnvPath });

const envReader = createRuntimeEnvReader(process.env);
const numberEnv = envReader.number.bind(envReader);
const booleanEnv = envReader.boolean.bind(envReader);
const enumEnv = envReader.enum.bind(envReader);

export const env = {
  REDIS_URL: process.env.REDIS_URL ?? "redis://127.0.0.1:6380",
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN ?? "",
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID ?? "",
  AUTO_RIA_API_KEY: process.env.AUTO_RIA_API_KEY ?? "",
  AUTO_RIA_TOTAL_REQUEST_LIMIT: numberEnv("AUTO_RIA_TOTAL_REQUEST_LIMIT", 1000),
  AUTO_RIA_HOURLY_REQUEST_LIMIT: numberEnv("AUTO_RIA_HOURLY_REQUEST_LIMIT", 30),
  AUTO_RIA_SOFT_RESERVE: numberEnv("AUTO_RIA_SOFT_RESERVE", 100),
  AUTO_RIA_MIN_SEARCH_RESERVE: numberEnv("AUTO_RIA_MIN_SEARCH_RESERVE", 50),
  AUTO_RIA_MAX_INFO_PER_SCAN: numberEnv("AUTO_RIA_MAX_INFO_PER_SCAN", 10),
  AUTO_RIA_PAID_ENRICHMENT_ENABLED: booleanEnv("AUTO_RIA_PAID_ENRICHMENT_ENABLED", false),
  FAKE_VEHICLE_CHECK_ENABLED: booleanEnv("FAKE_VEHICLE_CHECK_ENABLED", false),
  OLX_MAX_NEW_PER_RUN: numberEnv("OLX_MAX_NEW_PER_RUN", 250),
  // The public OLX web API rejects limit > 50 and offset > 1000 (verified 2026-07-17).
  OLX_API_PAGE_SIZE: numberEnv("OLX_API_PAGE_SIZE", 50),
  OLX_API_MAX_OFFSET: numberEnv("OLX_API_MAX_OFFSET", 1000),
  OLX_KNOWN_IDS_RESET_THRESHOLD: numberEnv("OLX_KNOWN_IDS_RESET_THRESHOLD", 2_000),
  OLX_REALTIME_MAX_PAGES: numberEnv("OLX_REALTIME_MAX_PAGES", 1),
  OLX_PRIVATE_FEED_ENABLED: booleanEnv("OLX_PRIVATE_FEED_ENABLED", false),
  OLX_BACKFILL_MAX_PAGES: numberEnv("OLX_BACKFILL_MAX_PAGES", 20),
  OLX_MIN_EXPECTED_PAGE_ITEMS: numberEnv("OLX_MIN_EXPECTED_PAGE_ITEMS", 10),
  OLX_REQUEST_TIMEOUT_MS: numberEnv("OLX_REQUEST_TIMEOUT_MS", 8_000),
  OLX_COVERAGE_INTERVAL_SECONDS: numberEnv("OLX_COVERAGE_INTERVAL_SECONDS", 60),
  OLX_COVERAGE_MAX_DURATION_MS: numberEnv("OLX_COVERAGE_MAX_DURATION_MS", 30_000),
  OLX_HTML_COVERAGE_INTERVAL_SECONDS: numberEnv("OLX_HTML_COVERAGE_INTERVAL_SECONDS", 60),
  OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS: numberEnv("OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS", 90),
  OLX_HTML_DETAIL_MAX_PER_SCAN: numberEnv("OLX_HTML_DETAIL_MAX_PER_SCAN", 6),
  OLX_BACKFILL_PAGE_DELAY_MS: numberEnv("OLX_BACKFILL_PAGE_DELAY_MS", 750),
  OLX_BACKFILL_REALTIME_QUIET_MS: numberEnv("OLX_BACKFILL_REALTIME_QUIET_MS", 250),
  // Background traffic is deliberately slower than the 4s realtime cadence.
  // The coordinator applies this only to coverage/backfill/recovery/enrichment.
  OLX_BACKGROUND_REQUEST_MIN_INTERVAL_MS: numberEnv("OLX_BACKGROUND_REQUEST_MIN_INTERVAL_MS", 3_500),
  OLX_BACKGROUND_AFTER_REALTIME_QUIET_MS: numberEnv("OLX_BACKGROUND_AFTER_REALTIME_QUIET_MS", 1_000),
  // The origin remains serialized. Only consecutive realtime requests may
  // reduce the post-finish floor after a clean, measured qualification window.
  OLX_REALTIME_QUIET_CANARY_ENABLED: booleanEnv("OLX_REALTIME_QUIET_CANARY_ENABLED", true),
  OLX_REALTIME_QUIET_CANARY_CANDIDATE_MS: numberEnv("OLX_REALTIME_QUIET_CANARY_CANDIDATE_MS", 150),
  OLX_REALTIME_QUIET_CANARY_QUALIFICATION_REQUESTS: numberEnv("OLX_REALTIME_QUIET_CANARY_QUALIFICATION_REQUESTS", 100),
  OLX_REALTIME_QUIET_CANARY_EVALUATION_REQUESTS: numberEnv("OLX_REALTIME_QUIET_CANARY_EVALUATION_REQUESTS", 30),
  OLX_REALTIME_QUIET_CANARY_P95_GROWTH_PERCENT: numberEnv("OLX_REALTIME_QUIET_CANARY_P95_GROWTH_PERCENT", 120),
  OLX_REALTIME_QUIET_CANARY_QUEUE_DEPTH_LIMIT: numberEnv("OLX_REALTIME_QUIET_CANARY_QUEUE_DEPTH_LIMIT", 25),
  OLX_PROTECTION_COOLING_SECONDS: numberEnv("OLX_PROTECTION_COOLING_SECONDS", 30 * 60),
  OLX_OUTAGE_DETECTION_SECONDS: numberEnv("OLX_OUTAGE_DETECTION_SECONDS", 120),
  OLX_OUTAGE_RECOVERY_LOOKBACK_HOURS: numberEnv("OLX_OUTAGE_RECOVERY_LOOKBACK_HOURS", 48),
  OLX_OUTAGE_SAFETY_OVERLAP_SECONDS: numberEnv("OLX_OUTAGE_SAFETY_OVERLAP_SECONDS", 300),
  // Hunting mode: also treat freshly re-listed / bumped OLX adverts as fresh
  // (uses the newer of created_time / last_refresh_time as the publish time).
  // Off by default — it surfaces reseller re-posts and price drops, at the cost
  // of some extra notifications.
  OLX_INCLUDE_REFRESHED: booleanEnv("OLX_INCLUDE_REFRESHED", false),
  MARKET_RESEARCH_OLX_MAX_PAGES: numberEnv("MARKET_RESEARCH_OLX_MAX_PAGES", 4),
  MARKET_RESEARCH_MAX_COMPARABLES: numberEnv("MARKET_RESEARCH_MAX_COMPARABLES", 160),
  MARKET_RESEARCH_CACHE_TTL_SECONDS: numberEnv("MARKET_RESEARCH_CACHE_TTL_SECONDS", 6 * 60 * 60),
  MARKET_RESEARCH_DEADLINE_MS: numberEnv("MARKET_RESEARCH_DEADLINE_MS", 12_000),
  RST_SEARCH_URL: process.env.RST_SEARCH_URL ?? "https://rst.ua/ukr/oldcars/",
  CARS_UA_SEARCH_URL: process.env.CARS_UA_SEARCH_URL ?? "https://cars.ua/",
  // Cars.ua is a fast source (near-instant indexing). Realtime paginates
  // adaptively until it overlaps already-known adverts, so bursts are not lost.
  CARS_UA_MAX_NEW_PER_RUN: numberEnv("CARS_UA_MAX_NEW_PER_RUN", 40),
  CARS_UA_REALTIME_MAX_PAGES: numberEnv("CARS_UA_REALTIME_MAX_PAGES", 3),
  AUTOMOTO_SEARCH_URL: process.env.AUTOMOTO_SEARCH_URL ?? "https://automoto.ua/uk/car?order=addDate",
  AUTOMOTO_REQUEST_TIMEOUT_MS: numberEnv("AUTOMOTO_REQUEST_TIMEOUT_MS", 8_000),
  PRICE_UAH_PER_USD: numberEnv("PRICE_UAH_PER_USD", 44.65),
  INITIAL_WINDOW_BEHAVIOR: enumEnv("INITIAL_WINDOW_BEHAVIOR", ["SKIP_EXISTING", "NOTIFY_MATCHING_IN_WINDOW"] as const, "SKIP_EXISTING"),
  MAX_INITIAL_WINDOW_NOTIFICATIONS: numberEnv("MAX_INITIAL_WINDOW_NOTIFICATIONS", 50),
  KNOWN_LISTING_STOP_THRESHOLD: numberEnv("KNOWN_LISTING_STOP_THRESHOLD", 10),
  REALTIME_MAX_CANDIDATES: numberEnv("REALTIME_MAX_CANDIDATES", 250),
  BACKFILL_MAX_PAGES: numberEnv("BACKFILL_MAX_PAGES", 4),
  BACKFILL_MAX_CANDIDATES: numberEnv("BACKFILL_MAX_CANDIDATES", 800),
  BACKFILL_MAX_DURATION_MS: numberEnv("BACKFILL_MAX_DURATION_MS", 90_000),
  SOURCE_EMPTY_RESULT_WARNING_THRESHOLD: numberEnv("SOURCE_EMPTY_RESULT_WARNING_THRESHOLD", 3),
  COLLECTOR_LOCK_RETRY_MAX: numberEnv("COLLECTOR_LOCK_RETRY_MAX", 3),
  COLLECTOR_LOCK_RETRY_DELAY_MS: numberEnv("COLLECTOR_LOCK_RETRY_DELAY_MS", 750),
  HOT_DUPLICATE_TTL_SECONDS: numberEnv("HOT_DUPLICATE_TTL_SECONDS", 120),
  STARTUP_RECOVERY_LIMIT: numberEnv("STARTUP_RECOVERY_LIMIT", 500),
  PIPELINE_RECOVERY_INTERVAL_MS: numberEnv("PIPELINE_RECOVERY_INTERVAL_MS", 2 * 60 * 1000),
  OBSERVATION_REPLAY_INTERVAL_MS: numberEnv("OBSERVATION_REPLAY_INTERVAL_MS", 30_000),
  OBSERVATION_REPLAY_LOOKBACK_HOURS: numberEnv("OBSERVATION_REPLAY_LOOKBACK_HOURS", 48),
  OBSERVATION_REPLAY_LIMIT: numberEnv("OBSERVATION_REPLAY_LIMIT", 500),
  RETENTION_INTERVAL_MS: numberEnv("RETENTION_INTERVAL_MS", 6 * 60 * 60 * 1000),
  RETENTION_COLLECTOR_RUN_DAYS: numberEnv("RETENTION_COLLECTOR_RUN_DAYS", 7),
  RETENTION_ERROR_LOG_DAYS: numberEnv("RETENTION_ERROR_LOG_DAYS", 90),
  RETENTION_AUDIT_DAYS: numberEnv("RETENTION_AUDIT_DAYS", 90),
  RETENTION_OBSERVATION_DAYS: numberEnv("RETENTION_OBSERVATION_DAYS", 365),
  LISTING_RETENTION_HOURS: numberEnv("LISTING_RETENTION_HOURS", 12),
  LISTING_FAVORITE_RETENTION_DAYS: numberEnv("LISTING_FAVORITE_RETENTION_DAYS", 10),
  LISTING_CLEANUP_INTERVAL_MS: numberEnv("LISTING_CLEANUP_INTERVAL_MS", 5 * 60 * 1000),
  LISTING_CLEANUP_BATCH_SIZE: numberEnv("LISTING_CLEANUP_BATCH_SIZE", 50),
  MAX_SCAN_DURATION_MS: numberEnv("MAX_SCAN_DURATION_MS", 20_000),
  RATE_LIMIT_PAUSE_BASE_SECONDS: numberEnv("RATE_LIMIT_PAUSE_BASE_SECONDS", 90),
  RATE_LIMIT_PAUSE_MAX_SECONDS: numberEnv("RATE_LIMIT_PAUSE_MAX_SECONDS", 60 * 60),
  CAPTCHA_PAUSE_SECONDS: numberEnv("CAPTCHA_PAUSE_SECONDS", 900),
  CAPTCHA_PAUSE_MAX_SECONDS: numberEnv("CAPTCHA_PAUSE_MAX_SECONDS", 3600),
  SOURCE_HTTP_USER_AGENT:
    process.env.SOURCE_HTTP_USER_AGENT ??
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
  SOURCE_HTTP_TIMEOUT_MS: numberEnv("SOURCE_HTTP_TIMEOUT_MS", 10_000),
  SOURCE_HTTP_MAX_RESPONSE_BYTES: numberEnv("SOURCE_HTTP_MAX_RESPONSE_BYTES", 5_000_000),
  SOURCE_HTTP_CONNECTIONS_PER_ORIGIN: numberEnv("SOURCE_HTTP_CONNECTIONS_PER_ORIGIN", 4),
  SOURCE_HTTP_TRANSIENT_RETRY_COUNT: numberEnv("SOURCE_HTTP_TRANSIENT_RETRY_COUNT", 3),
  SOURCE_HTTP_TRANSIENT_RETRY_BASE_DELAY_MS: numberEnv("SOURCE_HTTP_TRANSIENT_RETRY_BASE_DELAY_MS", 1_000),
  FAST_INLINE_TELEGRAM_SEND_ENABLED: booleanEnv("FAST_INLINE_TELEGRAM_SEND_ENABLED", true),
  FAST_INLINE_LISTING_PROCESSING_ENABLED: booleanEnv("FAST_INLINE_LISTING_PROCESSING_ENABLED", true),
  FAST_INLINE_LISTING_LIMIT_PER_RUN: numberEnv("FAST_INLINE_LISTING_LIMIT_PER_RUN", 1),
  FAST_INLINE_LISTING_CONCURRENCY: numberEnv("FAST_INLINE_LISTING_CONCURRENCY", 4),
  FAST_INLINE_TELEGRAM_DEADLINE_MS: numberEnv("FAST_INLINE_TELEGRAM_DEADLINE_MS", 4_000),
  TELEGRAM_FLASH_BUNDLE_ENABLED: booleanEnv("TELEGRAM_FLASH_BUNDLE_ENABLED", true),
  TELEGRAM_FLASH_BUNDLE_MIN_ITEMS: numberEnv("TELEGRAM_FLASH_BUNDLE_MIN_ITEMS", 2),
  TELEGRAM_FLASH_BUNDLE_MAX_ITEMS: numberEnv("TELEGRAM_FLASH_BUNDLE_MAX_ITEMS", 20),
  TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS: numberEnv("TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS", 1_100),
  WORKER_CONCURRENCY_TELEGRAM_FLASH: numberEnv("WORKER_CONCURRENCY_TELEGRAM_FLASH", 1),
  WORKER_CONCURRENCY_TELEGRAM_SEND: numberEnv("WORKER_CONCURRENCY_TELEGRAM_SEND", 6),
  WORKER_CONCURRENCY_TELEGRAM_UPDATE: numberEnv("WORKER_CONCURRENCY_TELEGRAM_UPDATE", 4),
  WORKER_CONCURRENCY_LISTING_DETECTED: numberEnv("WORKER_CONCURRENCY_LISTING_DETECTED", 6),
  WORKER_CONCURRENCY_LISTING_ENRICH: numberEnv("WORKER_CONCURRENCY_LISTING_ENRICH", 3),
  WORKER_CONCURRENCY_VEHICLE_CHECK: numberEnv("WORKER_CONCURRENCY_VEHICLE_CHECK", 3),
  WORKER_CONCURRENCY_COLLECTOR_RUN: numberEnv("WORKER_CONCURRENCY_COLLECTOR_RUN", 3),
  WORKER_CONCURRENCY_COLLECTOR_COVERAGE: numberEnv("WORKER_CONCURRENCY_COLLECTOR_COVERAGE", 1),
  WORKER_CONCURRENCY_COLLECTOR_BACKFILL: numberEnv("WORKER_CONCURRENCY_COLLECTOR_BACKFILL", 1),
  WORKER_CONCURRENCY_OBSERVATION_REPLAY: numberEnv("WORKER_CONCURRENCY_OBSERVATION_REPLAY", 1),
  NHTSA_VPIC_ENABLED: booleanEnv("NHTSA_VPIC_ENABLED", true),
  NHTSA_VPIC_TIMEOUT_MS: numberEnv("NHTSA_VPIC_TIMEOUT_MS", 3_000),
  NHTSA_RECALLS_ENABLED: booleanEnv("NHTSA_RECALLS_ENABLED", true),
  NHTSA_RECALLS_TIMEOUT_MS: numberEnv("NHTSA_RECALLS_TIMEOUT_MS", 3_000),
  NHTSA_COMPLAINTS_ENABLED: booleanEnv("NHTSA_COMPLAINTS_ENABLED", true),
  NHTSA_COMPLAINTS_TIMEOUT_MS: numberEnv("NHTSA_COMPLAINTS_TIMEOUT_MS", 3_000),
  NHTSA_SAFETY_RATINGS_ENABLED: booleanEnv("NHTSA_SAFETY_RATINGS_ENABLED", true),
  NHTSA_SAFETY_RATINGS_TIMEOUT_MS: numberEnv("NHTSA_SAFETY_RATINGS_TIMEOUT_MS", 3_000),
  DATA_GOV_UA_STOLEN_ENABLED: booleanEnv("DATA_GOV_UA_STOLEN_ENABLED", true),
  DATA_GOV_UA_STOLEN_TIMEOUT_MS: numberEnv("DATA_GOV_UA_STOLEN_TIMEOUT_MS", 8_000),
  DATA_GOV_UA_STOLEN_CACHE_MS: numberEnv("DATA_GOV_UA_STOLEN_CACHE_MS", 6 * 60 * 60 * 1000),
  DATA_GOV_UA_STOLEN_URL:
    process.env.DATA_GOV_UA_STOLEN_URL ??
    "https://data.gov.ua/dataset/2cd12755-834b-4c43-9026-fe356ce93af5/resource/2d69d196-02f1-49b9-97fa-0fb69077e05f/download/carswanted.json",
  PHOTO_IDENTIFIER_OCR_ENABLED: booleanEnv("PHOTO_IDENTIFIER_OCR_ENABLED", true),
  PHOTO_IDENTIFIER_OCR_MAX_IMAGES: numberEnv("PHOTO_IDENTIFIER_OCR_MAX_IMAGES", 2),
  PHOTO_IDENTIFIER_OCR_MAX_BYTES: numberEnv("PHOTO_IDENTIFIER_OCR_MAX_BYTES", 8_000_000),
  PHOTO_IDENTIFIER_OCR_DOWNLOAD_TIMEOUT_MS: numberEnv("PHOTO_IDENTIFIER_OCR_DOWNLOAD_TIMEOUT_MS", 5_000),
  PHOTO_IDENTIFIER_OCR_RECOGNIZE_TIMEOUT_MS: numberEnv("PHOTO_IDENTIFIER_OCR_RECOGNIZE_TIMEOUT_MS", 12_000),
} as const;

assertIntegerRange("OLX_MAX_NEW_PER_RUN", env.OLX_MAX_NEW_PER_RUN, 1, 2_000);
assertIntegerRange("OLX_API_PAGE_SIZE", env.OLX_API_PAGE_SIZE, 1, 50);
assertIntegerRange("OLX_API_MAX_OFFSET", env.OLX_API_MAX_OFFSET, 0, 1_000);
assertIntegerRange("OLX_KNOWN_IDS_RESET_THRESHOLD", env.OLX_KNOWN_IDS_RESET_THRESHOLD, 1, 2_000);
assertIntegerRange("OLX_REALTIME_MAX_PAGES", env.OLX_REALTIME_MAX_PAGES, 1, 20);
assertIntegerRange("OLX_BACKFILL_MAX_PAGES", env.OLX_BACKFILL_MAX_PAGES, 1, 100);
assertIntegerRange("OLX_REQUEST_TIMEOUT_MS", env.OLX_REQUEST_TIMEOUT_MS, 1_000, 60_000);
assertIntegerRange("OLX_COVERAGE_INTERVAL_SECONDS", env.OLX_COVERAGE_INTERVAL_SECONDS, 15, 3_600);
assertIntegerRange("OLX_COVERAGE_MAX_DURATION_MS", env.OLX_COVERAGE_MAX_DURATION_MS, 5_000, 120_000);
assertIntegerRange("OLX_HTML_COVERAGE_INTERVAL_SECONDS", env.OLX_HTML_COVERAGE_INTERVAL_SECONDS, 30, 3_600);
assertIntegerRange("OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS", env.OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS, 30, 3_600);
assertIntegerRange("OLX_HTML_DETAIL_MAX_PER_SCAN", env.OLX_HTML_DETAIL_MAX_PER_SCAN, 0, 20);
assertIntegerRange("OLX_BACKFILL_PAGE_DELAY_MS", env.OLX_BACKFILL_PAGE_DELAY_MS, 250, 10_000);
assertIntegerRange("OLX_BACKFILL_REALTIME_QUIET_MS", env.OLX_BACKFILL_REALTIME_QUIET_MS, 0, 2_000);
assertIntegerRange("OLX_BACKGROUND_REQUEST_MIN_INTERVAL_MS", env.OLX_BACKGROUND_REQUEST_MIN_INTERVAL_MS, 3_000, 10_000);
assertIntegerRange("OLX_BACKGROUND_AFTER_REALTIME_QUIET_MS", env.OLX_BACKGROUND_AFTER_REALTIME_QUIET_MS, 0, 1_000);
assertIntegerRange("OLX_REALTIME_QUIET_CANARY_CANDIDATE_MS", env.OLX_REALTIME_QUIET_CANARY_CANDIDATE_MS, 0, 349);
assertIntegerRange("OLX_REALTIME_QUIET_CANARY_QUALIFICATION_REQUESTS", env.OLX_REALTIME_QUIET_CANARY_QUALIFICATION_REQUESTS, 20, 10_000);
assertIntegerRange("OLX_REALTIME_QUIET_CANARY_EVALUATION_REQUESTS", env.OLX_REALTIME_QUIET_CANARY_EVALUATION_REQUESTS, 10, 1_000);
assertIntegerRange("OLX_REALTIME_QUIET_CANARY_P95_GROWTH_PERCENT", env.OLX_REALTIME_QUIET_CANARY_P95_GROWTH_PERCENT, 100, 300);
assertIntegerRange("OLX_REALTIME_QUIET_CANARY_QUEUE_DEPTH_LIMIT", env.OLX_REALTIME_QUIET_CANARY_QUEUE_DEPTH_LIMIT, 1, 100);
assertIntegerRange("OLX_PROTECTION_COOLING_SECONDS", env.OLX_PROTECTION_COOLING_SECONDS, 60, 24 * 60 * 60);
assertIntegerRange("OLX_OUTAGE_DETECTION_SECONDS", env.OLX_OUTAGE_DETECTION_SECONDS, 30, 86_400);
assertIntegerRange("OLX_OUTAGE_RECOVERY_LOOKBACK_HOURS", env.OLX_OUTAGE_RECOVERY_LOOKBACK_HOURS, 1, 168);
assertIntegerRange("OLX_OUTAGE_SAFETY_OVERLAP_SECONDS", env.OLX_OUTAGE_SAFETY_OVERLAP_SECONDS, 0, 3_600);
assertIntegerRange("OLX_MIN_EXPECTED_PAGE_ITEMS", env.OLX_MIN_EXPECTED_PAGE_ITEMS, 1, 50);
assertIntegerRange("REALTIME_MAX_CANDIDATES", env.REALTIME_MAX_CANDIDATES, 1, 5_000);
assertIntegerRange("BACKFILL_MAX_PAGES", env.BACKFILL_MAX_PAGES, 1, 100);
assertIntegerRange("BACKFILL_MAX_CANDIDATES", env.BACKFILL_MAX_CANDIDATES, 1, 20_000);
assertIntegerRange("BACKFILL_MAX_DURATION_MS", env.BACKFILL_MAX_DURATION_MS, 5_000, 10 * 60 * 1000);
assertIntegerRange("WORKER_CONCURRENCY_COLLECTOR_COVERAGE", env.WORKER_CONCURRENCY_COLLECTOR_COVERAGE, 1, 4);
assertIntegerRange("FAST_INLINE_LISTING_LIMIT_PER_RUN", env.FAST_INLINE_LISTING_LIMIT_PER_RUN, 0, 250);
assertIntegerRange("FAST_INLINE_LISTING_CONCURRENCY", env.FAST_INLINE_LISTING_CONCURRENCY, 1, 16);
assertIntegerRange("FAST_INLINE_TELEGRAM_DEADLINE_MS", env.FAST_INLINE_TELEGRAM_DEADLINE_MS, 500, 10_000);
assertIntegerRange("TELEGRAM_FLASH_BUNDLE_MIN_ITEMS", env.TELEGRAM_FLASH_BUNDLE_MIN_ITEMS, 2, 20);
assertIntegerRange("TELEGRAM_FLASH_BUNDLE_MAX_ITEMS", env.TELEGRAM_FLASH_BUNDLE_MAX_ITEMS, 2, 50);
assertNumberOrder(
  "TELEGRAM_FLASH_BUNDLE_MIN_ITEMS",
  env.TELEGRAM_FLASH_BUNDLE_MIN_ITEMS,
  "TELEGRAM_FLASH_BUNDLE_MAX_ITEMS",
  env.TELEGRAM_FLASH_BUNDLE_MAX_ITEMS,
);
assertIntegerRange("WORKER_CONCURRENCY_TELEGRAM_FLASH", env.WORKER_CONCURRENCY_TELEGRAM_FLASH, 1, 2);
assertIntegerRange("TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS", env.TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS, 250, 5_000);
assertIntegerRange("SOURCE_HTTP_TIMEOUT_MS", env.SOURCE_HTTP_TIMEOUT_MS, 1_000, 60_000);
assertIntegerRange("SOURCE_HTTP_MAX_RESPONSE_BYTES", env.SOURCE_HTTP_MAX_RESPONSE_BYTES, 64_000, 50_000_000);
assertIntegerRange("SOURCE_HTTP_CONNECTIONS_PER_ORIGIN", env.SOURCE_HTTP_CONNECTIONS_PER_ORIGIN, 4, 16);
assertIntegerRange("SOURCE_HTTP_TRANSIENT_RETRY_COUNT", env.SOURCE_HTTP_TRANSIENT_RETRY_COUNT, 0, 5);
assertIntegerRange("SOURCE_HTTP_TRANSIENT_RETRY_BASE_DELAY_MS", env.SOURCE_HTTP_TRANSIENT_RETRY_BASE_DELAY_MS, 100, 10_000);
assertIntegerRange("PHOTO_IDENTIFIER_OCR_MAX_BYTES", env.PHOTO_IDENTIFIER_OCR_MAX_BYTES, 64_000, 25_000_000);
assertIntegerRange("LISTING_RETENTION_HOURS", env.LISTING_RETENTION_HOURS, 1, 48);
assertIntegerRange("LISTING_FAVORITE_RETENTION_DAYS", env.LISTING_FAVORITE_RETENTION_DAYS, 1, 30);
assertIntegerRange("LISTING_CLEANUP_INTERVAL_MS", env.LISTING_CLEANUP_INTERVAL_MS, 60_000, 24 * 60 * 60 * 1000);
assertIntegerRange("LISTING_CLEANUP_BATCH_SIZE", env.LISTING_CLEANUP_BATCH_SIZE, 1, 500);
for (const [key, value, min, max] of [
  ["AUTO_RIA_TOTAL_REQUEST_LIMIT", env.AUTO_RIA_TOTAL_REQUEST_LIMIT, 1, 1_000_000],
  ["AUTO_RIA_HOURLY_REQUEST_LIMIT", env.AUTO_RIA_HOURLY_REQUEST_LIMIT, 1, 100_000],
  ["AUTO_RIA_SOFT_RESERVE", env.AUTO_RIA_SOFT_RESERVE, 0, 1_000_000],
  ["AUTO_RIA_MIN_SEARCH_RESERVE", env.AUTO_RIA_MIN_SEARCH_RESERVE, 0, 1_000_000],
  ["AUTO_RIA_MAX_INFO_PER_SCAN", env.AUTO_RIA_MAX_INFO_PER_SCAN, 0, 1_000],
  ["MARKET_RESEARCH_OLX_MAX_PAGES", env.MARKET_RESEARCH_OLX_MAX_PAGES, 1, 10],
  ["MARKET_RESEARCH_MAX_COMPARABLES", env.MARKET_RESEARCH_MAX_COMPARABLES, 1, 1_000],
  ["MARKET_RESEARCH_CACHE_TTL_SECONDS", env.MARKET_RESEARCH_CACHE_TTL_SECONDS, 60, 7 * 24 * 60 * 60],
  ["MARKET_RESEARCH_DEADLINE_MS", env.MARKET_RESEARCH_DEADLINE_MS, 2_000, 60_000],
  ["CARS_UA_MAX_NEW_PER_RUN", env.CARS_UA_MAX_NEW_PER_RUN, 1, 2_000],
  ["CARS_UA_REALTIME_MAX_PAGES", env.CARS_UA_REALTIME_MAX_PAGES, 1, 20],
  ["AUTOMOTO_REQUEST_TIMEOUT_MS", env.AUTOMOTO_REQUEST_TIMEOUT_MS, 1_000, 60_000],
  ["MAX_INITIAL_WINDOW_NOTIFICATIONS", env.MAX_INITIAL_WINDOW_NOTIFICATIONS, 0, 5_000],
  ["KNOWN_LISTING_STOP_THRESHOLD", env.KNOWN_LISTING_STOP_THRESHOLD, 1, 1_000],
  ["SOURCE_EMPTY_RESULT_WARNING_THRESHOLD", env.SOURCE_EMPTY_RESULT_WARNING_THRESHOLD, 1, 1_000],
  ["COLLECTOR_LOCK_RETRY_MAX", env.COLLECTOR_LOCK_RETRY_MAX, 0, 20],
  ["COLLECTOR_LOCK_RETRY_DELAY_MS", env.COLLECTOR_LOCK_RETRY_DELAY_MS, 100, 30_000],
  ["HOT_DUPLICATE_TTL_SECONDS", env.HOT_DUPLICATE_TTL_SECONDS, 60, 30 * 24 * 60 * 60],
  ["STARTUP_RECOVERY_LIMIT", env.STARTUP_RECOVERY_LIMIT, 1, 10_000],
  ["PIPELINE_RECOVERY_INTERVAL_MS", env.PIPELINE_RECOVERY_INTERVAL_MS, 10_000, 24 * 60 * 60 * 1000],
  ["OBSERVATION_REPLAY_INTERVAL_MS", env.OBSERVATION_REPLAY_INTERVAL_MS, 10_000, 24 * 60 * 60 * 1000],
  ["OBSERVATION_REPLAY_LOOKBACK_HOURS", env.OBSERVATION_REPLAY_LOOKBACK_HOURS, 1, 24 * 30],
  ["OBSERVATION_REPLAY_LIMIT", env.OBSERVATION_REPLAY_LIMIT, 1, 10_000],
  ["RETENTION_INTERVAL_MS", env.RETENTION_INTERVAL_MS, 60_000, 7 * 24 * 60 * 60 * 1000],
  ["RETENTION_COLLECTOR_RUN_DAYS", env.RETENTION_COLLECTOR_RUN_DAYS, 1, 365],
  ["RETENTION_ERROR_LOG_DAYS", env.RETENTION_ERROR_LOG_DAYS, 1, 3_650],
  ["RETENTION_AUDIT_DAYS", env.RETENTION_AUDIT_DAYS, 1, 3_650],
  ["RETENTION_OBSERVATION_DAYS", env.RETENTION_OBSERVATION_DAYS, 1, 3_650],
  ["MAX_SCAN_DURATION_MS", env.MAX_SCAN_DURATION_MS, 2_000, 5 * 60 * 1000],
  ["RATE_LIMIT_PAUSE_BASE_SECONDS", env.RATE_LIMIT_PAUSE_BASE_SECONDS, 30, 24 * 60 * 60],
  ["RATE_LIMIT_PAUSE_MAX_SECONDS", env.RATE_LIMIT_PAUSE_MAX_SECONDS, 30, 7 * 24 * 60 * 60],
  ["CAPTCHA_PAUSE_SECONDS", env.CAPTCHA_PAUSE_SECONDS, 60, 24 * 60 * 60],
  ["CAPTCHA_PAUSE_MAX_SECONDS", env.CAPTCHA_PAUSE_MAX_SECONDS, 60, 7 * 24 * 60 * 60],
  ["NHTSA_VPIC_TIMEOUT_MS", env.NHTSA_VPIC_TIMEOUT_MS, 500, 60_000],
  ["NHTSA_RECALLS_TIMEOUT_MS", env.NHTSA_RECALLS_TIMEOUT_MS, 500, 60_000],
  ["NHTSA_COMPLAINTS_TIMEOUT_MS", env.NHTSA_COMPLAINTS_TIMEOUT_MS, 500, 60_000],
  ["NHTSA_SAFETY_RATINGS_TIMEOUT_MS", env.NHTSA_SAFETY_RATINGS_TIMEOUT_MS, 500, 60_000],
  ["DATA_GOV_UA_STOLEN_TIMEOUT_MS", env.DATA_GOV_UA_STOLEN_TIMEOUT_MS, 1_000, 120_000],
  ["DATA_GOV_UA_STOLEN_CACHE_MS", env.DATA_GOV_UA_STOLEN_CACHE_MS, 60_000, 30 * 24 * 60 * 60 * 1000],
  ["PHOTO_IDENTIFIER_OCR_MAX_IMAGES", env.PHOTO_IDENTIFIER_OCR_MAX_IMAGES, 0, 20],
  ["PHOTO_IDENTIFIER_OCR_DOWNLOAD_TIMEOUT_MS", env.PHOTO_IDENTIFIER_OCR_DOWNLOAD_TIMEOUT_MS, 500, 60_000],
  ["PHOTO_IDENTIFIER_OCR_RECOGNIZE_TIMEOUT_MS", env.PHOTO_IDENTIFIER_OCR_RECOGNIZE_TIMEOUT_MS, 1_000, 120_000],
] as const) {
  assertIntegerRange(key, value, min, max);
}
assertNumberRange("PRICE_UAH_PER_USD", env.PRICE_UAH_PER_USD, 1, 200);
assertNumberOrder(
  "RATE_LIMIT_PAUSE_BASE_SECONDS",
  env.RATE_LIMIT_PAUSE_BASE_SECONDS,
  "RATE_LIMIT_PAUSE_MAX_SECONDS",
  env.RATE_LIMIT_PAUSE_MAX_SECONDS,
);
assertNumberOrder(
  "CAPTCHA_PAUSE_SECONDS",
  env.CAPTCHA_PAUSE_SECONDS,
  "CAPTCHA_PAUSE_MAX_SECONDS",
  env.CAPTCHA_PAUSE_MAX_SECONDS,
);
assertNumberOrder(
  "AUTO_RIA_SOFT_RESERVE",
  env.AUTO_RIA_SOFT_RESERVE,
  "AUTO_RIA_TOTAL_REQUEST_LIMIT",
  env.AUTO_RIA_TOTAL_REQUEST_LIMIT,
);
for (const [key, value] of Object.entries({
  WORKER_CONCURRENCY_TELEGRAM_SEND: env.WORKER_CONCURRENCY_TELEGRAM_SEND,
  WORKER_CONCURRENCY_TELEGRAM_UPDATE: env.WORKER_CONCURRENCY_TELEGRAM_UPDATE,
  WORKER_CONCURRENCY_LISTING_DETECTED: env.WORKER_CONCURRENCY_LISTING_DETECTED,
  WORKER_CONCURRENCY_LISTING_ENRICH: env.WORKER_CONCURRENCY_LISTING_ENRICH,
  WORKER_CONCURRENCY_VEHICLE_CHECK: env.WORKER_CONCURRENCY_VEHICLE_CHECK,
  WORKER_CONCURRENCY_COLLECTOR_RUN: env.WORKER_CONCURRENCY_COLLECTOR_RUN,
  WORKER_CONCURRENCY_COLLECTOR_BACKFILL: env.WORKER_CONCURRENCY_COLLECTOR_BACKFILL,
  WORKER_CONCURRENCY_OBSERVATION_REPLAY: env.WORKER_CONCURRENCY_OBSERVATION_REPLAY,
})) {
  assertIntegerRange(key, value, 1, 64);
}
