packages:
  - "apps/*"
  - "packages/*"

overrides:
  hono: 4.12.25
  ioredis: 5.11.1

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
