export const QUEUE_NAMES = {
  LISTING_DETECTED: "listing.detected",
  TELEGRAM_SEND: "telegram.send",
  LISTING_ENRICH: "listing.enrich",
  VEHICLE_CHECK: "vehicle.check",
  TELEGRAM_UPDATE: "telegram.update",
  COLLECTOR_RUN: "collector.run",
  COLLECTOR_BACKFILL: "collector.backfill",
  OBSERVATION_REPLAY: "observation.replay",
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];

export const REALTIME_LISTING_PRIORITY = 1;
export const TELEGRAM_SEND_PRIORITY = 1;
export const CURRENT_PAGE_PRIORITY = 2;
export const LAST_24_HOURS_BACKFILL_PRIORITY = 10;
export const BACKFILL_TELEGRAM_PRIORITY = 8;
export const ENRICHMENT_PRIORITY = 20;
export const METRICS_PRIORITY = 50;

export const QUEUE_PRIORITIES: Record<QueueName, number> = {
  [QUEUE_NAMES.TELEGRAM_SEND]: TELEGRAM_SEND_PRIORITY,
  [QUEUE_NAMES.LISTING_DETECTED]: REALTIME_LISTING_PRIORITY,
  [QUEUE_NAMES.TELEGRAM_UPDATE]: 4,
  [QUEUE_NAMES.LISTING_ENRICH]: ENRICHMENT_PRIORITY,
  [QUEUE_NAMES.VEHICLE_CHECK]: ENRICHMENT_PRIORITY,
  [QUEUE_NAMES.COLLECTOR_RUN]: 8,
  [QUEUE_NAMES.COLLECTOR_BACKFILL]: LAST_24_HOURS_BACKFILL_PRIORITY,
  [QUEUE_NAMES.OBSERVATION_REPLAY]: 6,
};
