export const FILTER_REJECTION_REASONS = [
  "FILTER_DISABLED",
  "SOURCE",
  "FRESHNESS",
  "BRAND",
  "MODEL",
  "GENERATION",
  "BODY_TYPE",
  "FUEL_TYPE",
  "GEARBOX",
  "DRIVE_TYPE",
  "COLOR",
  "CONDITION",
  "YEAR",
  "ENGINE_VOLUME",
  "ENGINE_POWER",
  "DOORS",
  "SEATS",
  "PRICE",
  "MILEAGE",
  "CUSTOMS",
  "BARGAIN",
  "GEOGRAPHY",
  "EXCLUDED_KEYWORD",
  "REQUIRED_KEYWORD",
  "NO_ENABLED_FILTERS",
  "SOURCE_NO_LONGER_AVAILABLE",
] as const;

export type FilterRejectionReason = (typeof FILTER_REJECTION_REASONS)[number];

export const FILTER_REJECTION_LABELS: Record<FilterRejectionReason, string> = {
  FILTER_DISABLED: "фильтр выключен",
  SOURCE: "источник не выбран",
  FRESHNESS: "объявление вне выбранного периода",
  BRAND: "не совпала марка",
  MODEL: "не совпала модель",
  GENERATION: "не совпало поколение",
  BODY_TYPE: "не совпал кузов",
  FUEL_TYPE: "не совпало топливо",
  GEARBOX: "не совпала коробка передач",
  DRIVE_TYPE: "не совпал привод",
  COLOR: "не совпал цвет",
  CONDITION: "не совпало состояние",
  YEAR: "год вне диапазона",
  ENGINE_VOLUME: "объем двигателя вне диапазона",
  ENGINE_POWER: "мощность вне диапазона",
  DOORS: "число дверей вне диапазона",
  SEATS: "число мест вне диапазона",
  PRICE: "цена вне диапазона",
  MILEAGE: "пробег вне диапазона",
  CUSTOMS: "не совпал статус растаможки",
  BARGAIN: "не совпала возможность торга",
  GEOGRAPHY: "город или область не выбраны",
  EXCLUDED_KEYWORD: "найдено исключающее слово",
  REQUIRED_KEYWORD: "нет обязательного слова",
  NO_ENABLED_FILTERS: "нет подходящих активных фильтров",
  SOURCE_NO_LONGER_AVAILABLE: "карточка больше не доступна в источнике",
};
