import { cn } from "@/lib/utils"

type Tone = "success" | "warning" | "danger" | "accent" | "muted"

const TONE_CLASSES: Record<Tone, string> = {
  success: "border-success/30 bg-success/10 text-success",
  warning: "border-warning/30 bg-warning/10 text-warning",
  danger: "border-danger/30 bg-danger/10 text-danger",
  accent: "border-accent/30 bg-accent/10 text-accent-soft",
  muted: "border-border bg-panel-alt text-muted",
}

const STATUS_TONES: Record<string, Tone> = {
  OK: "success",
  RUNNING: "success",
  ACTIVE: "success",
  ENABLED: "success",
  CONNECTED: "success",
  LINK_OK: "success",
  SUCCESS: "success",
  SENT: "success",
  UPDATED: "success",
  CHECK_DONE: "success",
  BELOW_MARKET: "success",
  FAIR: "success",
  STARTING: "accent",
  MATCHED: "accent",
  ENRICHED: "accent",
  VALIDATING: "accent",
  PENDING: "warning",
  PAUSED: "warning",
  LIMITED: "warning",
  RATE_LIMITED: "warning",
  WARN: "warning",
  CHECK_PARTIAL: "warning",
  NO_PLATE_OR_VIN_FOUND: "warning",
  ABOVE_MARKET: "warning",
  UNVERIFIED: "warning",
  BRIDGE_REQUIRED: "warning",
  BOT_OR_WEBHOOK_REQUIRED: "warning",
  WEBHOOK_REQUIRED: "warning",
  STALE: "warning",
  LINK_EXPIRED: "warning",
  FLOOD_WAIT: "warning",
  ERROR: "danger",
  FAILED: "danger",
  CAPTCHA_DETECTED: "danger",
  CHECK_FAILED: "danger",
  HIGH_RISK_BARGAIN: "danger",
  PRIVATE_ACCESS_REQUIRED: "danger",
  USER_NOT_JOINED: "danger",
  NOT_FOUND: "danger",
  STOPPED: "muted",
  DISABLED: "muted",
  UNKNOWN: "muted",
  NO_SEND: "muted",
  NO_CHECK: "muted",
  MANUAL_ONLY: "muted",
  DEVICE_BRIDGE: "muted",
  CUSTOM_WEBHOOK: "muted",
  NOT_CONFIGURED: "muted",
  INACTIVE: "muted",
  DISCONNECTED: "muted",
  NEW: "muted",
  NOT_STARTED: "muted",
  INFO: "muted",
  "DEVELOPMENT DATA": "warning",
}

const STATUS_LABELS: Record<string, string> = {
  OK: "OK",
  RUNNING: "РАБОТАЕТ",
  ACTIVE: "АКТИВЕН",
  ENABLED: "ВКЛЮЧЕН",
  CONNECTED: "ПОДКЛЮЧЕН",
  LINK_OK: "ССЫЛКА ОК",
  SUCCESS: "УСПЕХ",
  SENT: "ОТПРАВЛЕНО",
  UPDATED: "ОБНОВЛЕНО",
  CHECK_DONE: "ПРОВЕРЕНО",
  STARTING: "СТАРТ",
  MATCHED: "СОВПАЛО",
  ENRICHED: "ДОПОЛНЕНО",
  PENDING: "ОЖИДАЕТ",
  PAUSED: "ПАУЗА",
  LIMITED: "ЛИМИТ",
  RATE_LIMITED: "ЛИМИТ",
  WARN: "ВНИМАНИЕ",
  CHECK_PARTIAL: "ЧАСТИЧНО",
  NO_PLATE_OR_VIN_FOUND: "НЕТ НОМЕРА/VIN",
  ERROR: "ОШИБКА",
  FAILED: "СБОЙ",
  CAPTCHA_DETECTED: "CAPTCHA",
  CHECK_FAILED: "СБОЙ ПРОВЕРКИ",
  STOPPED: "ОСТАНОВЛЕН",
  DISABLED: "ВЫКЛЮЧЕН",
  UNKNOWN: "НЕИЗВЕСТНО",
  NO_SEND: "НЕТ ОТПРАВКИ",
  NO_CHECK: "НЕТ ПРОВЕРКИ",
  NEW: "НОВОЕ",
  NOT_STARTED: "НЕ СТАРТОВАЛО",
  INFO: "INFO",
  "DEVELOPMENT DATA": "ТЕСТОВЫЕ ДАННЫЕ",
  HIGH_RISK_BARGAIN: "СИЛЬНО НИЖЕ РЫНКА",
  BELOW_MARKET: "НИЖЕ РЫНКА",
  FAIR: "РЫНОК",
  ABOVE_MARKET: "ВЫШЕ РЫНКА",
  MANUAL_ONLY: "РУЧНОЙ",
  DEVICE_BRIDGE: "BRIDGE",
  CUSTOM_WEBHOOK: "WEBHOOK",
  NOT_CONFIGURED: "НЕ НАСТРОЕН",
  BRIDGE_REQUIRED: "НУЖЕН BRIDGE",
  BOT_OR_WEBHOOK_REQUIRED: "НУЖЕН БОТ",
  WEBHOOK_REQUIRED: "НУЖЕН WEBHOOK",
  STALE: "НЕТ СВЯЗИ",
  LINK_EXPIRED: "ССЫЛКА УСТАРЕЛА",
  UNVERIFIED: "НЕ ПРОВЕРЕН",
  VALIDATING: "ПРОВЕРКА",
  INACTIVE: "НЕАКТИВЕН",
  PRIVATE_ACCESS_REQUIRED: "НУЖЕН ДОСТУП",
  USER_NOT_JOINED: "НЕ ВСТУПИЛ",
  NOT_FOUND: "НЕ НАЙДЕН",
  FLOOD_WAIT: "FLOOD WAIT",
  DISCONNECTED: "ОТКЛЮЧЕН",
}

export function StatusBadge({ status, className }: { status: string; className?: string }) {
  const tone = STATUS_TONES[status] ?? "muted"
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 font-mono text-[11px] font-medium tracking-wide",
        TONE_CLASSES[tone],
        className,
      )}
    >
      <span
        className={cn("size-1.5 rounded-full", {
          "bg-success animate-pulse-glow": tone === "success",
          "bg-warning": tone === "warning",
          "bg-danger": tone === "danger",
          "bg-accent": tone === "accent",
          "bg-muted": tone === "muted",
        })}
      />
      {STATUS_LABELS[status] ?? status}
    </span>
  )
}
