import path from "node:path";
import { fileURLToPath } from "node:url";
import { config } from "dotenv";
import { assertIntegerRange, assertNumberOrder, createRuntimeEnvReader } from "@amb/shared";

const rootEnvPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..", ".env");
config({ path: rootEnvPath });

const envReader = createRuntimeEnvReader(process.env);
const numberEnv = envReader.number.bind(envReader);
const booleanEnv = envReader.boolean.bind(envReader);
const enumEnv = envReader.enum.bind(envReader);

export const env = {
  API_PORT: numberEnv("API_PORT", 4000),
  API_HOST: process.env.API_HOST ?? "127.0.0.1",
  DASHBOARD_ORIGIN: process.env.DASHBOARD_ORIGIN ?? "http://localhost:3001",
  LOCAL_API_TOKEN: process.env.LOCAL_API_TOKEN ?? "",
  API_REQUIRE_LOCAL_TOKEN_FOR_ALL: booleanEnv("API_REQUIRE_LOCAL_TOKEN_FOR_ALL", true),
  REDIS_URL: process.env.REDIS_URL ?? "redis://127.0.0.1:6380",
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN ?? "",
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID ?? "",
  TELEGRAM_CONTROL_BOT_ENABLED: booleanEnv("TELEGRAM_CONTROL_BOT_ENABLED", true),
  TELEGRAM_CONTROL_NOTIFY_ON_START: booleanEnv("TELEGRAM_CONTROL_NOTIFY_ON_START", true),
  TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS: numberEnv("TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS", 1_100),
  TELEGRAM_FLASH_BUNDLE_ENABLED: booleanEnv("TELEGRAM_FLASH_BUNDLE_ENABLED", true),
  TELEGRAM_FLASH_BUNDLE_MIN_ITEMS: numberEnv("TELEGRAM_FLASH_BUNDLE_MIN_ITEMS", 2),
  TELEGRAM_FLASH_BUNDLE_MAX_ITEMS: numberEnv("TELEGRAM_FLASH_BUNDLE_MAX_ITEMS", 20),
  WORKER_CONCURRENCY_TELEGRAM_FLASH: numberEnv("WORKER_CONCURRENCY_TELEGRAM_FLASH", 1),
  AUTO_RIA_API_KEY: process.env.AUTO_RIA_API_KEY ?? "",
  AUTO_RIA_USER_ID: process.env.AUTO_RIA_USER_ID ?? "",
  AUTO_RIA_TOTAL_REQUEST_LIMIT: numberEnv("AUTO_RIA_TOTAL_REQUEST_LIMIT", 1000),
  AUTO_RIA_HOURLY_REQUEST_LIMIT: numberEnv("AUTO_RIA_HOURLY_REQUEST_LIMIT", 30),
  AUTO_RIA_SOFT_RESERVE: numberEnv("AUTO_RIA_SOFT_RESERVE", 100),
  AUTO_RIA_MIN_SEARCH_RESERVE: numberEnv("AUTO_RIA_MIN_SEARCH_RESERVE", 50),
  AUTO_RIA_MAX_INFO_PER_SCAN: numberEnv("AUTO_RIA_MAX_INFO_PER_SCAN", 10),
  AUTO_RIA_PAID_ENRICHMENT_ENABLED: booleanEnv("AUTO_RIA_PAID_ENRICHMENT_ENABLED", false),
  AUTO_RIA_VIN_LOOKUP_ENABLED: booleanEnv("AUTO_RIA_VIN_LOOKUP_ENABLED", false),
  AUTO_RIA_AVERAGE_PRICE_ENABLED: booleanEnv("AUTO_RIA_AVERAGE_PRICE_ENABLED", false),
  MOCK_SOURCE_ENABLED: booleanEnv("MOCK_SOURCE_ENABLED", false),
  MONITOR_INTERVAL_SECONDS: numberEnv("MONITOR_INTERVAL_SECONDS", 120),
  MONITOR_JITTER_SECONDS: numberEnv("MONITOR_JITTER_SECONDS", 20),
  SCHEDULER_MIN_SLEEP_MS: numberEnv("SCHEDULER_MIN_SLEEP_MS", 100),
  SCHEDULER_MAX_SLEEP_MS: numberEnv("SCHEDULER_MAX_SLEEP_MS", 1_000),
  BACKFILL_INTERVAL_SECONDS: numberEnv("BACKFILL_INTERVAL_SECONDS", 300),
  OLX_BACKFILL_MIN_INTERVAL_SECONDS: numberEnv("OLX_BACKFILL_MIN_INTERVAL_SECONDS", 15 * 60),
  BACKFILL_INITIAL_DELAY_SECONDS: numberEnv("BACKFILL_INITIAL_DELAY_SECONDS", 60),
  OLX_COVERAGE_INTERVAL_SECONDS: numberEnv("OLX_COVERAGE_INTERVAL_SECONDS", 60),
  OLX_COVERAGE_INITIAL_DELAY_SECONDS: numberEnv("OLX_COVERAGE_INITIAL_DELAY_SECONDS", 30),
  OLX_COVERAGE_MAX_DURATION_MS: numberEnv("OLX_COVERAGE_MAX_DURATION_MS", 30_000),
  BACKFILL_MAX_PAGES: numberEnv("BACKFILL_MAX_PAGES", 4),
  BACKFILL_MAX_CANDIDATES: numberEnv("BACKFILL_MAX_CANDIDATES", 800),
  BACKFILL_MAX_DURATION_MS: numberEnv("BACKFILL_MAX_DURATION_MS", 90_000),
  WORKER_CONCURRENCY_COLLECTOR_BACKFILL: numberEnv("WORKER_CONCURRENCY_COLLECTOR_BACKFILL", 1),
  WORKER_CONCURRENCY_COLLECTOR_COVERAGE: numberEnv("WORKER_CONCURRENCY_COLLECTOR_COVERAGE", 1),
  WORKER_HEARTBEAT_STALE_SECONDS: numberEnv("WORKER_HEARTBEAT_STALE_SECONDS", 10 * 60),
  // The measured p95 realtime run is below 18s. A 20s base cadence avoids
  // normal overlap while cutting the previous 60s detection delay by 3x.
  LIVE_OLX_INTERVAL_SECONDS: numberEnv("LIVE_OLX_INTERVAL_SECONDS", 20),
  LIVE_OLX_JITTER_SECONDS: numberEnv("LIVE_OLX_JITTER_SECONDS", 4),
  OLX_CADENCE_CANARY_ENABLED: booleanEnv("OLX_CADENCE_CANARY_ENABLED", true),
  OLX_CADENCE_CANARY_QUALIFICATION_RUNS: numberEnv("OLX_CADENCE_CANARY_QUALIFICATION_RUNS", 100),
  OLX_CADENCE_CANARY_PROMOTION_RUNS: numberEnv("OLX_CADENCE_CANARY_PROMOTION_RUNS", 100),
  OLX_CADENCE_CANARY_INTERVAL_SECONDS: numberEnv("OLX_CADENCE_CANARY_INTERVAL_SECONDS", 15),
  OLX_CADENCE_CANARY_JITTER_SECONDS: numberEnv("OLX_CADENCE_CANARY_JITTER_SECONDS", 3),
  OLX_CADENCE_CANARY_QUALIFICATION_MAX_P95_MS: numberEnv("OLX_CADENCE_CANARY_QUALIFICATION_MAX_P95_MS", 8_000),
  OLX_CADENCE_CANARY_MAX_P95_MS: numberEnv("OLX_CADENCE_CANARY_MAX_P95_MS", 12_000),
  OLX_CADENCE_CANARY_P95_MIN_SAMPLES: numberEnv("OLX_CADENCE_CANARY_P95_MIN_SAMPLES", 10),
  OLX_CADENCE_CANARY_P95_GROWTH_PERCENT: numberEnv("OLX_CADENCE_CANARY_P95_GROWTH_PERCENT", 125),
  OLX_CADENCE_CANARY_QUEUE_DEPTH_LIMIT: numberEnv("OLX_CADENCE_CANARY_QUEUE_DEPTH_LIMIT", 25),
  OLX_REALTIME_RECOVERY_RAMP_SECONDS: numberEnv("OLX_REALTIME_RECOVERY_RAMP_SECONDS", 30 * 60),
  OLX_HTML_COVERAGE_INTERVAL_SECONDS: numberEnv("OLX_HTML_COVERAGE_INTERVAL_SECONDS", 60),
  OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS: numberEnv("OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS", 90),
  LIVE_CARS_UA_INTERVAL_SECONDS: numberEnv("LIVE_CARS_UA_INTERVAL_SECONDS", 15),
  LIVE_CARS_UA_JITTER_SECONDS: numberEnv("LIVE_CARS_UA_JITTER_SECONDS", 3),
  LIVE_AUTOMOTO_INTERVAL_SECONDS: numberEnv("LIVE_AUTOMOTO_INTERVAL_SECONDS", 60),
  LIVE_AUTOMOTO_JITTER_SECONDS: numberEnv("LIVE_AUTOMOTO_JITTER_SECONDS", 10),
  LIVE_RST_INTERVAL_SECONDS: numberEnv("LIVE_RST_INTERVAL_SECONDS", 120),
  LIVE_RST_JITTER_SECONDS: numberEnv("LIVE_RST_JITTER_SECONDS", 20),
  LIVE_AUTO_RIA_MIN_INTERVAL_SECONDS: numberEnv("LIVE_AUTO_RIA_MIN_INTERVAL_SECONDS", 60),
  LIVE_AUTO_RIA_JITTER_SECONDS: numberEnv("LIVE_AUTO_RIA_JITTER_SECONDS", 5),
  AUTO_RIA_SEARCH_REQUESTS_PER_HOUR: numberEnv("AUTO_RIA_SEARCH_REQUESTS_PER_HOUR", 30),
  ALLOW_MANUAL_CHECK_WHEN_STOPPED: booleanEnv("ALLOW_MANUAL_CHECK_WHEN_STOPPED", true),
  MANUAL_CHECK_DEDUP_SECONDS: numberEnv("MANUAL_CHECK_DEDUP_SECONDS", 30),
  INITIAL_WINDOW_BEHAVIOR: enumEnv("INITIAL_WINDOW_BEHAVIOR", ["SKIP_EXISTING", "NOTIFY_MATCHING_IN_WINDOW"] as const, "SKIP_EXISTING"),
  MAX_INITIAL_WINDOW_NOTIFICATIONS: numberEnv("MAX_INITIAL_WINDOW_NOTIFICATIONS", 50),
  KNOWN_LISTING_STOP_THRESHOLD: numberEnv("KNOWN_LISTING_STOP_THRESHOLD", 10),
  LISTING_RETENTION_HOURS: numberEnv("LISTING_RETENTION_HOURS", 12),
  LISTING_FAVORITE_RETENTION_DAYS: numberEnv("LISTING_FAVORITE_RETENTION_DAYS", 10),
  LISTING_CLEANUP_INTERVAL_MS: numberEnv("LISTING_CLEANUP_INTERVAL_MS", 5 * 60 * 1000),
} as const;

assertIntegerRange("API_PORT", env.API_PORT, 1, 65_535);
assertIntegerRange("MONITOR_INTERVAL_SECONDS", env.MONITOR_INTERVAL_SECONDS, 1, 86_400);
assertIntegerRange("TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS", env.TELEGRAM_LISTING_SEND_MIN_INTERVAL_MS, 250, 5_000);
assertIntegerRange("TELEGRAM_FLASH_BUNDLE_MIN_ITEMS", env.TELEGRAM_FLASH_BUNDLE_MIN_ITEMS, 2, 20);
assertIntegerRange("TELEGRAM_FLASH_BUNDLE_MAX_ITEMS", env.TELEGRAM_FLASH_BUNDLE_MAX_ITEMS, 2, 50);
assertNumberOrder(
  "TELEGRAM_FLASH_BUNDLE_MIN_ITEMS",
  env.TELEGRAM_FLASH_BUNDLE_MIN_ITEMS,
  "TELEGRAM_FLASH_BUNDLE_MAX_ITEMS",
  env.TELEGRAM_FLASH_BUNDLE_MAX_ITEMS,
);
assertIntegerRange("WORKER_CONCURRENCY_TELEGRAM_FLASH", env.WORKER_CONCURRENCY_TELEGRAM_FLASH, 1, 2);
assertNumberOrder(
  "OLX_CADENCE_CANARY_INTERVAL_SECONDS",
  env.OLX_CADENCE_CANARY_INTERVAL_SECONDS,
  "LIVE_OLX_INTERVAL_SECONDS",
  env.LIVE_OLX_INTERVAL_SECONDS,
);
assertNumberOrder(
  "OLX_CADENCE_CANARY_QUALIFICATION_MAX_P95_MS",
  env.OLX_CADENCE_CANARY_QUALIFICATION_MAX_P95_MS,
  "OLX_CADENCE_CANARY_MAX_P95_MS",
  env.OLX_CADENCE_CANARY_MAX_P95_MS,
);
assertIntegerRange("SCHEDULER_MIN_SLEEP_MS", env.SCHEDULER_MIN_SLEEP_MS, 25, 60_000);
assertIntegerRange("SCHEDULER_MAX_SLEEP_MS", env.SCHEDULER_MAX_SLEEP_MS, 25, 60_000);
assertNumberOrder(
  "SCHEDULER_MIN_SLEEP_MS",
  env.SCHEDULER_MIN_SLEEP_MS,
  "SCHEDULER_MAX_SLEEP_MS",
  env.SCHEDULER_MAX_SLEEP_MS,
);
assertIntegerRange("BACKFILL_INTERVAL_SECONDS", env.BACKFILL_INTERVAL_SECONDS, 10, 86_400);
assertIntegerRange("OLX_COVERAGE_INTERVAL_SECONDS", env.OLX_COVERAGE_INTERVAL_SECONDS, 15, 3_600);
assertIntegerRange("OLX_COVERAGE_INITIAL_DELAY_SECONDS", env.OLX_COVERAGE_INITIAL_DELAY_SECONDS, 0, 3_600);
assertIntegerRange("OLX_COVERAGE_MAX_DURATION_MS", env.OLX_COVERAGE_MAX_DURATION_MS, 5_000, 120_000);
assertIntegerRange("OLX_BACKFILL_MIN_INTERVAL_SECONDS", env.OLX_BACKFILL_MIN_INTERVAL_SECONDS, 60, 86_400);
assertIntegerRange("BACKFILL_MAX_PAGES", env.BACKFILL_MAX_PAGES, 1, 100);
assertIntegerRange("BACKFILL_MAX_CANDIDATES", env.BACKFILL_MAX_CANDIDATES, 1, 10_000);
assertIntegerRange("WORKER_CONCURRENCY_COLLECTOR_BACKFILL", env.WORKER_CONCURRENCY_COLLECTOR_BACKFILL, 1, 16);
assertIntegerRange("WORKER_CONCURRENCY_COLLECTOR_COVERAGE", env.WORKER_CONCURRENCY_COLLECTOR_COVERAGE, 1, 4);
assertIntegerRange("LISTING_RETENTION_HOURS", env.LISTING_RETENTION_HOURS, 1, 48);
assertIntegerRange("LISTING_FAVORITE_RETENTION_DAYS", env.LISTING_FAVORITE_RETENTION_DAYS, 1, 30);
assertIntegerRange("LISTING_CLEANUP_INTERVAL_MS", env.LISTING_CLEANUP_INTERVAL_MS, 60_000, 24 * 60 * 60 * 1000);
for (const [key, value, min, max] of [
  ["AUTO_RIA_TOTAL_REQUEST_LIMIT", env.AUTO_RIA_TOTAL_REQUEST_LIMIT, 1, 1_000_000],
  ["AUTO_RIA_HOURLY_REQUEST_LIMIT", env.AUTO_RIA_HOURLY_REQUEST_LIMIT, 1, 100_000],
  ["AUTO_RIA_SOFT_RESERVE", env.AUTO_RIA_SOFT_RESERVE, 0, 1_000_000],
  ["AUTO_RIA_MIN_SEARCH_RESERVE", env.AUTO_RIA_MIN_SEARCH_RESERVE, 0, 1_000_000],
  ["AUTO_RIA_MAX_INFO_PER_SCAN", env.AUTO_RIA_MAX_INFO_PER_SCAN, 0, 1_000],
  ["BACKFILL_INITIAL_DELAY_SECONDS", env.BACKFILL_INITIAL_DELAY_SECONDS, 0, 3_600],
  ["BACKFILL_MAX_DURATION_MS", env.BACKFILL_MAX_DURATION_MS, 5_000, 10 * 60 * 1000],
  ["WORKER_HEARTBEAT_STALE_SECONDS", env.WORKER_HEARTBEAT_STALE_SECONDS, 10, 24 * 60 * 60],
  ["LIVE_OLX_INTERVAL_SECONDS", env.LIVE_OLX_INTERVAL_SECONDS, 3, 300],
  ["LIVE_OLX_JITTER_SECONDS", env.LIVE_OLX_JITTER_SECONDS, 0, 30],
  ["OLX_CADENCE_CANARY_QUALIFICATION_RUNS", env.OLX_CADENCE_CANARY_QUALIFICATION_RUNS, 100, 10_000],
  ["OLX_CADENCE_CANARY_PROMOTION_RUNS", env.OLX_CADENCE_CANARY_PROMOTION_RUNS, 10, 10_000],
  ["OLX_CADENCE_CANARY_INTERVAL_SECONDS", env.OLX_CADENCE_CANARY_INTERVAL_SECONDS, 3, 300],
  ["OLX_CADENCE_CANARY_JITTER_SECONDS", env.OLX_CADENCE_CANARY_JITTER_SECONDS, 0, 30],
  ["OLX_CADENCE_CANARY_QUALIFICATION_MAX_P95_MS", env.OLX_CADENCE_CANARY_QUALIFICATION_MAX_P95_MS, 1_000, 120_000],
  ["OLX_CADENCE_CANARY_MAX_P95_MS", env.OLX_CADENCE_CANARY_MAX_P95_MS, 1_000, 120_000],
  ["OLX_CADENCE_CANARY_P95_MIN_SAMPLES", env.OLX_CADENCE_CANARY_P95_MIN_SAMPLES, 5, 1_000],
  ["OLX_CADENCE_CANARY_P95_GROWTH_PERCENT", env.OLX_CADENCE_CANARY_P95_GROWTH_PERCENT, 100, 300],
  ["OLX_CADENCE_CANARY_QUEUE_DEPTH_LIMIT", env.OLX_CADENCE_CANARY_QUEUE_DEPTH_LIMIT, 1, 10_000],
  ["OLX_REALTIME_RECOVERY_RAMP_SECONDS", env.OLX_REALTIME_RECOVERY_RAMP_SECONDS, 60, 24 * 60 * 60],
  ["OLX_HTML_COVERAGE_INTERVAL_SECONDS", env.OLX_HTML_COVERAGE_INTERVAL_SECONDS, 30, 3_600],
  ["OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS", env.OLX_PRIVATE_COVERAGE_INTERVAL_SECONDS, 30, 3_600],
  ["LIVE_CARS_UA_INTERVAL_SECONDS", env.LIVE_CARS_UA_INTERVAL_SECONDS, 3, 3_600],
  ["LIVE_CARS_UA_JITTER_SECONDS", env.LIVE_CARS_UA_JITTER_SECONDS, 0, 300],
  ["LIVE_AUTOMOTO_INTERVAL_SECONDS", env.LIVE_AUTOMOTO_INTERVAL_SECONDS, 10, 24 * 60 * 60],
  ["LIVE_AUTOMOTO_JITTER_SECONDS", env.LIVE_AUTOMOTO_JITTER_SECONDS, 0, 3_600],
  ["LIVE_RST_INTERVAL_SECONDS", env.LIVE_RST_INTERVAL_SECONDS, 10, 24 * 60 * 60],
  ["LIVE_RST_JITTER_SECONDS", env.LIVE_RST_JITTER_SECONDS, 0, 3_600],
  ["LIVE_AUTO_RIA_MIN_INTERVAL_SECONDS", env.LIVE_AUTO_RIA_MIN_INTERVAL_SECONDS, 30, 24 * 60 * 60],
  ["LIVE_AUTO_RIA_JITTER_SECONDS", env.LIVE_AUTO_RIA_JITTER_SECONDS, 0, 3_600],
  ["AUTO_RIA_SEARCH_REQUESTS_PER_HOUR", env.AUTO_RIA_SEARCH_REQUESTS_PER_HOUR, 1, 100_000],
  ["MANUAL_CHECK_DEDUP_SECONDS", env.MANUAL_CHECK_DEDUP_SECONDS, 0, 3_600],
  ["MAX_INITIAL_WINDOW_NOTIFICATIONS", env.MAX_INITIAL_WINDOW_NOTIFICATIONS, 0, 5_000],
  ["KNOWN_LISTING_STOP_THRESHOLD", env.KNOWN_LISTING_STOP_THRESHOLD, 1, 1_000],
] as const) {
  assertIntegerRange(key, value, min, max);
}
assertNumberOrder(
  "AUTO_RIA_SOFT_RESERVE",
  env.AUTO_RIA_SOFT_RESERVE,
  "AUTO_RIA_TOTAL_REQUEST_LIMIT",
  env.AUTO_RIA_TOTAL_REQUEST_LIMIT,
);
