ALTER TYPE "SocialPlatform" ADD VALUE IF NOT EXISTS 'FACEBOOK';

ALTER TYPE "SocialSourceCategory" ADD VALUE IF NOT EXISTS 'FACEBOOK_GROUP';
ALTER TYPE "SocialSourceCategory" ADD VALUE IF NOT EXISTS 'FACEBOOK_PAGE';
